if ($ENV:PDAL_DRIVER_PATH) {
    $ENV:_CONDA_SET_PDAL_DRIVER_PATH=$ENV:PDAL_DRIVER_PATH
}

$PDAL_PLUGIN_PATH = (python -m pdal --pdal-plugin-path) -join "`n"

$ENV:PDAL_DRIVER_PATH="$ENV:PDAL_DRIVER_PATH;$PDAL_PLUGIN_PATH"
if (-Not (Test-Path $ENV:PDAL_DRIVER_PATH) ) {
     Remove-Item ENV:PDAL_DRIVER_PATH
}
