{% set name = "python-pdal" %}
{% set version = "3.0.1" %}
{% set sha256 = "4ca62a49d18891c52a7e31b76f25208eeeda011e55d9703daf546e2dbe5f1285" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - load.patch

build:
  number: 0
  skip: true  # [(win and vc<14) or py<36]


requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - pdal
    - pip
    - pybind11
    - numpy
    - scikit-build
  host:
    - python {{ python }}
    - pdal
    - numpy
    - pip
    - pybind11
    - scikit-build
  run:
    - python {{ python }}
    - numpy
    - pdal

test:
  commands:
    - python -c "import pdal"

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
