{% set name = "python-pdal" %}
{% set version = "3.0.2" %}
{% set sha256 = "8bb398a3e6b288014ced8c1635cf4e2358ef18b283943a8547af1b825e73130d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - load.patch

build:
  number: 2
  skip: true  # [(win and vc<14) or py<36]


requirements:
  build:
    - python  {{ python }}                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - make
    - pdal
    - pip
    - scikit-build
  host:
    - python {{ python }}
    - pdal
    - numpy
    - pip
    - pybind11
    - scikit-build
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - pdal
    - openssl

test:
  commands:
    - python -c "import pdal"

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
