{% set name = "python-pdal" %}
{% set version = "3.2.0" %}
{% set sha256 = "e47fd1d0a27c550050e1d55b82db1b46f6494188daf5e7fdaafa0a958ef0a8c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [(win and vc<14) or (py<36) or (py<38 and linux)]


requirements:
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}      # [osx]
  build:
    - {{ compiler('cxx') }}
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - curl
    - cmake
    - pdal

  host:
    - python
    - pdal
    - numpy
    - pip
    - pybind11
    - scikit-build
  run:
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pdal', max_pin='x.x') }}
    - python

test:
  commands:
    - python -c "import pdal"

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
