{% set name = "python-pdal" %}
{% set version = "2.2.2" %}
{% set sha256 = "d379e1ef4c8334b460f89576c373d00d842a1811f41e92380ef125b813ad8bb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [(win and vc<14) or py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - packaging
    - pdal
    - libgdal
    - gdal
    - pip
  run:
    - python 3.7
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pdal', max_pin='x.x') }}
    - {{ pin_compatible('libgdal', max_pin='x.x') }}
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - packaging

test:
  source_files:
    - test
  imports:
    - pdal
  commands:
    - cd test && python -m unittest test_pipeline

about:
  home: https://pdal.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL) Python Package'
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
