{% set name = "python-pdal" %}
{% set version = "2.4.2" %}
{% set sha256 = "c5c1304f7e0ce76f929b7a768c12629a7fd36e98996fd520d2a5a10101adb9ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [(win and vc<14) or py<36]


requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pdal
    - {{ pin_compatible('numpy') }}
    - scikit-build
    - pip
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pdal

test:
  commands:
    - python -c "import pdal"

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
