{% set name = "python-pdal" %}
{% set version = "2.1.6" %}
{% set sha256 = "ad5487ace649bad22ee94e63646e286d883c120c7c896aabdfb400dff4726f06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - libgdal  {{ gdal }}
    - python 3.6
    - numpy
    - cython
    - packaging
    - pdal 1.8.*
    - libgdal 2.3.*
    - pip
  run:
    - python 3.6
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pdal', max_pin='x.x') }}
    - {{ pin_compatible('libgdal', max_pin='x.x') }}
    - packaging

test:
  source_files:
    - test
  imports:
    - pdal
  commands:
    - cd test && python -m unittest test_pipeline

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL) Python Package'
  description: |
    Python package for the PDAL library.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
