{% set name = "python-pdal" %}
{% set version = "2.1.5" %}
{% set sha256 = "f90540fc25fbce772916ed7131612d1cef58e46865505dee0e50b15c3c5457ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - packaging
    - pdal 1.7.*
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pdal', max_pin='x.x') }}
    - packaging

test:
  source_files:
    - test
  imports:
    - pdal
  commands:
    - cd test && python -m unittest test_pipeline

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL) Python Package'
  description: |
    Python package for the PDAL library.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
