{% set name = "python-pdal" %}
{% set version = "3.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: b264ccd29d349ae2b911cafda8aae4ecafe464a1a62f6c02ad3bf038f660154d

build:
  number: 4
  skip: true  # [ppc64le or (py<39)]

requirements:
  run_constrained:   # [osx]
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - curl
    - cmake
    - pdal
    - ninja
    - scikit-build-core
  host:
    - python
    - libpdal-core
    - numpy
    - pybind11
    - scikit-build-core
    - pip
  run:
    - numpy
    - python

test:
  requires:
    - pip
    - pytest
  commands:
    - pip check
  imports:
    - pdal

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
