{% set name = "python-pdal" %}
{% set version = "2.3.3" %}
{% set sha256 = "a78787b97da3cff4266f3428acdbb4a55293d05b9f0a55bf144475e819189e0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [(win and vc<14) or py<36]


requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pdal
    - {{ pin_compatible('numpy') }}
    - scikit-build
    - pip
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pdal

test:
  commands:
    - python -c "import this"

about:
  home: https://pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  doc_url: https://pdal.io
  dev_url: https://github.com/PDAL/python

extra:
  recipe-maintainers:
    - chambbj
    - hobu
