schema_version: 1

context:
  name: python-pdal
  version: "3.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/PDAL/python/archive/${{ version }}.tar.gz
  sha256: 0f07e452e38f7a6bc0dee5b5d5affad898ac98a0861c2ad0c5ce7ab227760ce1

build:
  number: 0
  skip: match(python, "<3.10")

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - make
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11
        - scikit-build-core
    - curl
    - cmake
    - ninja
    - if: win
      then: m2-sed
    - if: unix
      then: sed
  host:
    - python
    - libpdal-core
    - numpy
    - pybind11
    - scikit-build-core
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - pdal
  - requirements:
      run:
        - pip
        - pytest
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  homepage: https://pdal.io
  repository: https://github.com/PDAL/python
  documentation: https://pdal.io

extra:
  recipe-maintainers:
    - chambbj
    - hobu
