schema_version: 1

context:
  name: python-pdal
  version: 3.4.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/PDAL/python/archive/${{ version }}.tar.gz
  sha256: b264ccd29d349ae2b911cafda8aae4ecafe464a1a62f6c02ad3bf038f660154d

build:
  number: 15
  skip: match(python, "<3.9")

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - make
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - if: build_platform != target_platform
      then: pybind11
    - curl
    - cmake
    - ninja
    - scikit-build-core
    - if: win
      then: m2-sed
    - if: unix
      then: sed
  host:
    - python
    - libpdal-core
    - numpy
    - pybind11
    - scikit-build-core
    - pip
  run:
    - numpy
    - python
  run_constraints:

tests:
  - python:
      imports:
        - pdal
  - requirements:
      run:
        - pip
        - pytest
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) Python Package
  description: |
    Python package for the PDAL library.
  homepage: https://pdal.io
  repository: https://github.com/PDAL/python
  documentation: https://pdal.io

extra:
  recipe-maintainers:
    - chambbj
    - hobu
