travis:
  secure:
    BINSTAR_TOKEN: c/vQGmmLahQrQBZkoC1oYUeNd+BoNF7QWUFffjQrhYXL2gB0HuNFmV02uPRR67idsGKV5iVI2mu8P6NvgH7SIwN+rV/DPgEbFxV8nma0MqQ2+sifgvMrDVwDzUMO+rpf5OQyxoRfgv+V3WFcNP6PYMP7RcM1Vl4uQro30H6gFvtTHuxKirKcm6D3ZacYej46+An4Dc1Zn2I94ugq2jnz5VH3C3qR9D7KN83+OD1EvhLn6xR6iATeJPbis0WRFi5WUfR0pj0wJhfaQCN1hQ9AhlrAs5KdjIW/CL8CVrZIxkYG5xi/X/zFqyzsqCceSlZF5R9t5+YBLdcOIOEsJnPAA2i5248o6hZONOY+nFeqmkmn0jYUFRfgGfBCkrwG0bVCYT6u/trwY7qPJAGNFdIEtJaOHew/78uLWUkXzolPzbDBY4xtRphJEwVpi9iWgMydUfCgqorpXgOCs+nWvOSDSHEGLrFgRyZr69NO4eNQAGkFtZHgw/k0yasd7e254IdO9fp95bcHV6g44Ys8sdAj8k8H0PNgXC6XmIUivrXcbcXrIKKdZ45erR4+nxirvD5RFMnjyA86PTF3zV9tksU4elm2v4exmIn2+tQd0j8TdfdFmcCnZ7sn8iK43NvuPgCzDRT3hQf5x4y0STQXlc2y28DaYMT/X4cn7Jy2W7o+nxc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
